import type { Profile, NewsItem, Announcement, CategoryInfo } from "./types"

export const profiles: Profile[] = [
  {
    id: "1",
    nom: "Diallo",
    prenom: "Amadou",
    email: "amadou.diallo@email.com",
    telephone: "+225 07 08 09 10",
    categorie: "cadre_administratif",
    secteur: "Finance",
    metier: "Directeur financier",
    niveauEtude: "Bac+5 (Master)",
    experience: "15 ans",
    bio: "Directeur financier avec une expertise en gestion budgetaire et audit des finances publiques. Engage dans le developpement economique local.",
    competences: ["Gestion financiere", "Audit", "Comptabilite publique", "Management"],
    localisation: "Quartier Administratif",
    statut: "valide",
    dateInscription: "2025-01-15",
  },
  {
    id: "2",
    nom: "Kouame",
    prenom: "Sylvie",
    email: "sylvie.kouame@email.com",
    telephone: "+225 05 12 34 56",
    categorie: "chef_entreprise",
    secteur: "Agroalimentaire",
    metier: "Directrice generale",
    niveauEtude: "Bac+5 (Master)",
    experience: "12 ans",
    bio: "Fondatrice et directrice de Saveurs Locales SARL, specialisee dans la transformation de produits agricoles locaux. Passionnee par l'entrepreneuriat feminin.",
    competences: ["Gestion d'entreprise", "Marketing", "Transformation alimentaire", "Leadership"],
    localisation: "Zone Industrielle",
    statut: "valide",
    dateInscription: "2025-02-03",
  },
  {
    id: "3",
    nom: "Toure",
    prenom: "Ibrahim",
    email: "ibrahim.toure@email.com",
    telephone: "+225 01 23 45 67",
    categorie: "cadre_technique",
    secteur: "BTP",
    metier: "Ingenieur civil",
    niveauEtude: "Bac+5 (Master)",
    experience: "10 ans",
    bio: "Ingenieur civil specialise dans la construction d'infrastructures routieres et hydrauliques. Implique dans les projets de developpement communautaire.",
    competences: ["Genie civil", "Gestion de projets", "AutoCAD", "Etudes techniques"],
    localisation: "Centre-ville",
    statut: "valide",
    dateInscription: "2025-01-28",
  },
  {
    id: "4",
    nom: "Bamba",
    prenom: "Fatou",
    email: "fatou.bamba@email.com",
    telephone: "+225 07 65 43 21",
    categorie: "artisan",
    secteur: "Artisanat",
    metier: "Tisserande traditionnelle",
    niveauEtude: "Formation professionnelle",
    experience: "20 ans",
    bio: "Artisane reconnue pour ses creations textiles traditionnelles. Formatrice au centre d'apprentissage communal et ambassadrice du patrimoine local.",
    competences: ["Tissage", "Teinture traditionnelle", "Formation", "Design textile"],
    localisation: "Quartier Artisanal",
    statut: "valide",
    dateInscription: "2025-03-10",
  },
  {
    id: "5",
    nom: "Kone",
    prenom: "Moussa",
    email: "moussa.kone@email.com",
    telephone: "+225 01 98 76 54",
    categorie: "commercant",
    secteur: "Commerce",
    metier: "Grossiste en produits alimentaires",
    niveauEtude: "Bac+2",
    experience: "18 ans",
    bio: "Grossiste en produits alimentaires avec un reseau de distribution dans la region. Membre actif de la chambre de commerce locale.",
    competences: ["Logistique", "Negociation commerciale", "Gestion de stocks", "Import-export"],
    localisation: "Marche Central",
    statut: "valide",
    dateInscription: "2025-02-15",
  },
  {
    id: "6",
    nom: "Ouattara",
    prenom: "Aissata",
    email: "aissata.ouattara@email.com",
    telephone: "+225 05 11 22 33",
    categorie: "jeune_entrepreneur",
    secteur: "Informatique",
    metier: "Fondatrice startup tech",
    niveauEtude: "Bac+3 (Licence)",
    experience: "3 ans",
    bio: "Jeune entrepreneuse dynamique, fondatrice de DigiLocal, une plateforme de commerce electronique pour les produits artisanaux locaux.",
    competences: ["Developpement web", "E-commerce", "Marketing digital", "UX Design"],
    localisation: "Quartier Numerique",
    statut: "valide",
    dateInscription: "2025-04-01",
  },
  {
    id: "7",
    nom: "Coulibaly",
    prenom: "Seydou",
    email: "seydou.coulibaly@email.com",
    telephone: "+225 07 44 55 66",
    categorie: "investisseur",
    secteur: "Finance",
    metier: "Investisseur immobilier",
    niveauEtude: "Bac+5 (Master)",
    experience: "25 ans",
    bio: "Investisseur immobilier de renom, partenaire de nombreux projets de developpement dans la commune. Membre du conseil economique local.",
    competences: ["Investissement immobilier", "Finance", "Analyse de marche", "Negociation"],
    localisation: "Quartier Residence",
    statut: "valide",
    dateInscription: "2025-01-05",
  },
  {
    id: "8",
    nom: "Traore",
    prenom: "Mariam",
    email: "mariam.traore@email.com",
    telephone: "+225 01 77 88 99",
    categorie: "cadre_administratif",
    secteur: "Education",
    metier: "Inspectrice de l'education",
    niveauEtude: "Bac+5 (Master)",
    experience: "20 ans",
    bio: "Inspectrice de l'education nationale avec une longue carriere dans la promotion de l'excellence scolaire. Engagee dans les reformes educatives locales.",
    competences: ["Administration scolaire", "Pedagogie", "Evaluation", "Formation continue"],
    localisation: "Quartier Administratif",
    statut: "valide",
    dateInscription: "2025-03-20",
  },
  {
    id: "9",
    nom: "Yao",
    prenom: "Kofi",
    email: "kofi.yao@email.com",
    telephone: "+225 05 33 44 55",
    categorie: "cadre_technique",
    secteur: "Energie",
    metier: "Ingenieur electrique",
    niveauEtude: "Bac+5 (Master)",
    experience: "8 ans",
    bio: "Ingenieur specialise dans les energies renouvelables et l'electrification rurale. Promoteur de l'energie solaire dans la commune.",
    competences: ["Energie solaire", "Electrification", "Gestion de projets", "Etudes d'impact"],
    localisation: "Zone Industrielle",
    statut: "en_attente",
    dateInscription: "2025-05-02",
  },
  {
    id: "10",
    nom: "Sangare",
    prenom: "Oumar",
    email: "oumar.sangare@email.com",
    telephone: "+225 07 22 11 00",
    categorie: "chef_entreprise",
    secteur: "Transport",
    metier: "PDG societe de transport",
    niveauEtude: "Bac+3 (Licence)",
    experience: "14 ans",
    bio: "Fondateur et PDG de TransCom Express, premiere societe de transport interurbain de la region. Employeur majeur de la commune.",
    competences: ["Logistique", "Management", "Gestion de flotte", "Planification strategique"],
    localisation: "Gare Routiere",
    statut: "valide",
    dateInscription: "2025-02-28",
  },
  {
    id: "11",
    nom: "Dembele",
    prenom: "Kadiatou",
    email: "kadiatou.dembele@email.com",
    telephone: "+225 01 55 66 77",
    categorie: "artisan",
    secteur: "Artisanat",
    metier: "Potiere ceramiste",
    niveauEtude: "Formation professionnelle",
    experience: "15 ans",
    bio: "Maitresse potiere, creant des oeuvres en ceramique traditionnelle. Anime des ateliers pour les jeunes du quartier.",
    competences: ["Ceramique", "Modelage", "Art traditionnel", "Enseignement"],
    localisation: "Quartier Artisanal",
    statut: "valide",
    dateInscription: "2025-04-12",
  },
  {
    id: "12",
    nom: "Sissoko",
    prenom: "Drissa",
    email: "drissa.sissoko@email.com",
    telephone: "+225 05 88 99 00",
    categorie: "commercant",
    secteur: "Commerce",
    metier: "Detaillant electronique",
    niveauEtude: "Bac",
    experience: "10 ans",
    bio: "Commercant specialise dans la vente de materiel electronique et telephonique. Fournisseur de reference dans le centre commercial.",
    competences: ["Vente", "Service client", "Gestion de stock", "Reparation electronique"],
    localisation: "Centre Commercial",
    statut: "en_attente",
    dateInscription: "2025-05-10",
  },
  {
    id: "13",
    nom: "Koffi",
    prenom: "Aya",
    email: "aya.koffi@email.com",
    telephone: "+225 07 11 22 33",
    categorie: "jeune_entrepreneur",
    secteur: "Agroalimentaire",
    metier: "Fondatrice - Jus naturels",
    niveauEtude: "Bac+3 (Licence)",
    experience: "2 ans",
    bio: "Jeune entrepreneuse passionnee par la nutrition. Sa marque 'Naturel Boost' propose des jus de fruits frais 100% locaux.",
    competences: ["Production alimentaire", "Marketing", "Distribution", "Innovation"],
    localisation: "Marche Central",
    statut: "valide",
    dateInscription: "2025-04-20",
  },
  {
    id: "14",
    nom: "Camara",
    prenom: "Bakary",
    email: "bakary.camara@email.com",
    telephone: "+225 01 44 55 66",
    categorie: "investisseur",
    secteur: "Agriculture",
    metier: "Investisseur agricole",
    niveauEtude: "Bac+5 (Master)",
    experience: "20 ans",
    bio: "Investisseur dans l'agriculture moderne avec des exploitations agricoles et des fermes dans la region. Promoteur de l'agriculture durable.",
    competences: ["Agriculture", "Investissement", "Developpement durable", "Supply chain"],
    localisation: "Zone Agricole",
    statut: "valide",
    dateInscription: "2025-01-20",
  },
  {
    id: "15",
    nom: "Dosso",
    prenom: "Aminata",
    email: "aminata.dosso@email.com",
    telephone: "+225 05 77 88 99",
    categorie: "cadre_administratif",
    secteur: "Sante",
    metier: "Directrice d'hopital",
    niveauEtude: "Bac+8 (Doctorat)",
    experience: "22 ans",
    bio: "Directrice de l'hopital general de la commune. Medecin de formation, elle a consacre sa carriere a l'amelioration des soins de sante locaux.",
    competences: ["Administration hospitaliere", "Medecine", "Gestion sanitaire", "Politique de sante"],
    localisation: "Quartier Hospitalier",
    statut: "valide",
    dateInscription: "2025-02-10",
  },
  {
    id: "16",
    nom: "Soro",
    prenom: "Lacina",
    email: "lacina.soro@email.com",
    telephone: "+225 07 33 22 11",
    categorie: "cadre_technique",
    secteur: "Informatique",
    metier: "Directeur des systemes d'information",
    niveauEtude: "Bac+5 (Master)",
    experience: "12 ans",
    bio: "Expert en transformation digitale des administrations publiques. Pilote la modernisation informatique de la commune.",
    competences: ["Architecture SI", "Cybersecurite", "Cloud computing", "Gestion de projets IT"],
    localisation: "Centre-ville",
    statut: "valide",
    dateInscription: "2025-03-05",
  },
  {
    id: "17",
    nom: "Fofana",
    prenom: "Mamadou",
    email: "mamadou.fofana@email.com",
    telephone: "+225 01 66 77 88",
    categorie: "chef_entreprise",
    secteur: "Industrie",
    metier: "Directeur usine textile",
    niveauEtude: "Bac+5 (Master)",
    experience: "18 ans",
    bio: "Dirige la plus grande unite de production textile de la region, employant plus de 200 personnes. Engagee dans la formation professionnelle des jeunes.",
    competences: ["Production industrielle", "Management RH", "Qualite", "Export"],
    localisation: "Zone Industrielle",
    statut: "rejete",
    dateInscription: "2025-04-30",
  },
  {
    id: "18",
    nom: "N'Guessan",
    prenom: "Akissi",
    email: "akissi.nguessan@email.com",
    telephone: "+225 05 99 88 77",
    categorie: "artisan",
    secteur: "Artisanat",
    metier: "Couturiere styliste",
    niveauEtude: "Formation professionnelle",
    experience: "12 ans",
    bio: "Couturiere et styliste de mode africaine. Ses creations melent tradition et modernite. Laureate du prix regional de l'artisanat.",
    competences: ["Couture", "Design de mode", "Broderie", "Formation"],
    localisation: "Quartier Artisanal",
    statut: "en_attente",
    dateInscription: "2025-05-15",
  },
  {
    id: "19",
    nom: "Diabate",
    prenom: "Souleymane",
    email: "souleymane.diabate@email.com",
    telephone: "+225 07 55 44 33",
    categorie: "commercant",
    secteur: "Tourisme",
    metier: "Gerant d'hotel",
    niveauEtude: "Bac+3 (Licence)",
    experience: "8 ans",
    bio: "Gerant de l'Hotel du Patrimoine, etablissement de reference pour les visiteurs de la commune. Promoteur du tourisme local et culturel.",
    competences: ["Hotellerie", "Tourisme", "Service client", "Gestion d'etablissement"],
    localisation: "Centre Touristique",
    statut: "valide",
    dateInscription: "2025-03-25",
  },
  {
    id: "20",
    nom: "Kouyate",
    prenom: "Nana",
    email: "nana.kouyate@email.com",
    telephone: "+225 01 22 33 44",
    categorie: "jeune_entrepreneur",
    secteur: "Services",
    metier: "Fondatrice agence digitale",
    niveauEtude: "Bac+3 (Licence)",
    experience: "4 ans",
    bio: "Fondatrice de DigitalCom, agence de communication digitale qui accompagne les entreprises locales dans leur presence en ligne.",
    competences: ["Reseaux sociaux", "Creation de contenu", "SEO", "Publicite en ligne"],
    localisation: "Quartier Numerique",
    statut: "valide",
    dateInscription: "2025-04-08",
  },
  {
    id: "21",
    nom: "Sow",
    prenom: "Boubacar",
    email: "boubacar.sow@email.com",
    telephone: "+225 05 44 33 22",
    categorie: "cadre_technique",
    secteur: "Agriculture",
    metier: "Agronome",
    niveauEtude: "Bac+8 (Doctorat)",
    experience: "16 ans",
    bio: "Agronome de renom specialise dans l'amelioration des rendements agricoles. Conseiller technique aupres des cooperatives paysannes de la region.",
    competences: ["Agronomie", "Recherche", "Conseil technique", "Developpement rural"],
    localisation: "Zone Agricole",
    statut: "valide",
    dateInscription: "2025-02-20",
  },
  {
    id: "22",
    nom: "Konate",
    prenom: "Rokia",
    email: "rokia.konate@email.com",
    telephone: "+225 07 88 77 66",
    categorie: "chef_entreprise",
    secteur: "Sante",
    metier: "Directrice clinique privee",
    niveauEtude: "Bac+8 (Doctorat)",
    experience: "15 ans",
    bio: "Medecin et directrice de la Clinique Esperance, offrant des soins de qualite accessibles. Engagee dans la sante maternelle et infantile.",
    competences: ["Medecine", "Gestion hospitaliere", "Sante publique", "Management"],
    localisation: "Quartier Hospitalier",
    statut: "valide",
    dateInscription: "2025-03-15",
  },
  {
    id: "23",
    nom: "Cisse",
    prenom: "Abdoulaye",
    email: "abdoulaye.cisse@email.com",
    telephone: "+225 01 33 44 55",
    categorie: "investisseur",
    secteur: "Industrie",
    metier: "Investisseur industriel",
    niveauEtude: "Bac+5 (Master)",
    experience: "30 ans",
    bio: "Investisseur industriel de la diaspora, partenaire strategique pour les projets de developpement economique de la commune. Philanthrope actif.",
    competences: ["Investissement", "Strategie d'entreprise", "Partenariats", "Philanthropie"],
    localisation: "Quartier Residence",
    statut: "valide",
    dateInscription: "2025-01-10",
  },
  {
    id: "24",
    nom: "Ballo",
    prenom: "Fatoumata",
    email: "fatoumata.ballo@email.com",
    telephone: "+225 05 66 55 44",
    categorie: "commercant",
    secteur: "Commerce",
    metier: "Grossiste en tissus",
    niveauEtude: "Bac",
    experience: "22 ans",
    bio: "Grossiste en tissus et pagnes, l'une des commercantes les plus influentes du marche central. Membre du bureau des commercants.",
    competences: ["Commerce de gros", "Import", "Negociation", "Gestion de stock"],
    localisation: "Marche Central",
    statut: "valide",
    dateInscription: "2025-02-05",
  },
  {
    id: "25",
    nom: "Meite",
    prenom: "Hassan",
    email: "hassan.meite@email.com",
    telephone: "+225 07 99 88 77",
    categorie: "jeune_entrepreneur",
    secteur: "Agriculture",
    metier: "Fondateur ferme avicole",
    niveauEtude: "Bac+2",
    experience: "3 ans",
    bio: "Jeune entrepreneur dans l'aviculture moderne. Sa ferme produit plus de 5000 oeufs par jour et emploie 15 jeunes de la commune.",
    competences: ["Aviculture", "Gestion de ferme", "Entrepreneuriat", "Distribution"],
    localisation: "Zone Agricole",
    statut: "en_attente",
    dateInscription: "2025-05-20",
  },
]

export const newsItems: NewsItem[] = [
  {
    id: "n1",
    titre: "Inauguration du nouveau marche central",
    resume: "Le maire a inaugure le nouveau marche central qui permettra d'accueillir plus de 500 commercants dans des conditions modernes.",
    contenu: "Le nouveau marche central, fruit d'un investissement de 2 milliards de FCFA, offre des infrastructures modernes avec des espaces refrigeres, des sanitaires et un parking de 200 places.",
    type: "evenement",
    date: "2025-05-15",
  },
  {
    id: "n2",
    titre: "Programme de formation pour les jeunes entrepreneurs",
    resume: "La mairie lance un programme de formation gratuit pour les jeunes de 18 a 35 ans souhaitant creer leur entreprise.",
    contenu: "Ce programme de 6 mois couvre la gestion d'entreprise, le marketing digital, la comptabilite et l'acces au financement. Les inscriptions sont ouvertes jusqu'au 30 juin.",
    type: "annonce",
    date: "2025-05-10",
  },
  {
    id: "n3",
    titre: "Croissance de 15% du secteur artisanal",
    resume: "Le secteur artisanal de la commune a enregistre une croissance de 15% grace aux initiatives de valorisation du patrimoine.",
    contenu: "Cette croissance est portee par l'augmentation des exportations et le developpement du tourisme culturel. Plus de 200 emplois ont ete crees dans le secteur.",
    type: "economie",
    date: "2025-05-05",
  },
  {
    id: "n4",
    titre: "Forum economique communal 2025",
    resume: "La 3eme edition du forum economique reunira investisseurs, entrepreneurs et cadres pour definir les priorites de developpement.",
    contenu: "Le forum se tiendra les 20 et 21 juin au palais des congres. Au programme : panels, ateliers, mise en relation B2B et signature de conventions.",
    type: "evenement",
    date: "2025-04-28",
  },
  {
    id: "n5",
    titre: "Nouveaux financements pour les PME locales",
    resume: "Un partenariat avec la banque regionale permet de proposer des prets a taux reduits pour les petites et moyennes entreprises.",
    contenu: "Les entreprises de la commune peuvent desormais beneficier de prets allant de 1 a 50 millions de FCFA a un taux preferentiel de 5%.",
    type: "economie",
    date: "2025-04-20",
  },
  {
    id: "n6",
    titre: "Appel a candidatures : Incubateur communal",
    resume: "L'incubateur communal recherche 20 porteurs de projets innovants pour sa prochaine promotion.",
    contenu: "L'incubateur offre un accompagnement de 12 mois comprenant mentorat, espace de travail, formations et acces a un reseau d'investisseurs.",
    type: "annonce",
    date: "2025-04-15",
  },
]

export const announcements: Announcement[] = [
  {
    id: "a1",
    titre: "Mise a jour des profils obligatoire",
    contenu: "Tous les operateurs economiques sont invites a mettre a jour leurs informations avant le 30 juin 2025.",
    cible: "tous",
    date: "2025-05-18",
    auteur: "Direction du developpement economique",
  },
  {
    id: "a2",
    titre: "Formation en gestion numerique",
    contenu: "Session de formation gratuite en outils numeriques pour les artisans le 25 mai au centre communal.",
    cible: "artisan",
    date: "2025-05-12",
    auteur: "Service de la formation professionnelle",
  },
  {
    id: "a3",
    titre: "Appel a investissement - Zone Industrielle",
    contenu: "De nouveaux lots sont disponibles dans la zone industrielle. Conditions preferentielles pour les investisseurs locaux.",
    cible: "investisseur",
    date: "2025-05-08",
    auteur: "Direction de l'urbanisme",
  },
]

export const categoriesInfo: CategoryInfo[] = [
  {
    id: "cadre_administratif",
    label: "Cadres administratifs",
    description: "Fonctionnaires et cadres de l'administration publique locale et nationale",
    icon: "Briefcase",
    count: profiles.filter((p) => p.categorie === "cadre_administratif").length,
  },
  {
    id: "cadre_technique",
    label: "Cadres techniques",
    description: "Ingenieurs, techniciens et specialistes dans divers domaines techniques",
    icon: "Wrench",
    count: profiles.filter((p) => p.categorie === "cadre_technique").length,
  },
  {
    id: "chef_entreprise",
    label: "Chefs d'entreprise",
    description: "Dirigeants de PME, PMI et grandes entreprises operant dans la commune",
    icon: "Building2",
    count: profiles.filter((p) => p.categorie === "chef_entreprise").length,
  },
  {
    id: "artisan",
    label: "Artisans",
    description: "Artisans qualifies exercant des metiers traditionnels ou modernes",
    icon: "Hammer",
    count: profiles.filter((p) => p.categorie === "artisan").length,
  },
  {
    id: "commercant",
    label: "Commercants",
    description: "Commercants detaillants et grossistes actifs dans le tissu economique local",
    icon: "ShoppingBag",
    count: profiles.filter((p) => p.categorie === "commercant").length,
  },
  {
    id: "jeune_entrepreneur",
    label: "Jeunes entrepreneurs",
    description: "Porteurs de projets innovants et createurs de startups locales",
    icon: "Rocket",
    count: profiles.filter((p) => p.categorie === "jeune_entrepreneur").length,
  },
  {
    id: "investisseur",
    label: "Investisseurs / Partenaires",
    description: "Investisseurs et partenaires strategiques pour le developpement local",
    icon: "TrendingUp",
    count: profiles.filter((p) => p.categorie === "investisseur").length,
  },
]

export function getProfilesByCategory(category: string) {
  return profiles.filter((p) => p.categorie === category)
}

export function getProfileById(id: string) {
  return profiles.find((p) => p.id === id)
}

export function getProfilesByStatus(status: string) {
  return profiles.filter((p) => p.statut === status)
}

export function getStats() {
  const total = profiles.length
  const valides = profiles.filter((p) => p.statut === "valide").length
  const enAttente = profiles.filter((p) => p.statut === "en_attente").length
  const rejetes = profiles.filter((p) => p.statut === "rejete").length

  const parSecteur = profiles.reduce(
    (acc, p) => {
      acc[p.secteur] = (acc[p.secteur] || 0) + 1
      return acc
    },
    {} as Record<string, number>
  )

  const parCategorie = profiles.reduce(
    (acc, p) => {
      acc[p.categorie] = (acc[p.categorie] || 0) + 1
      return acc
    },
    {} as Record<string, number>
  )

  const parNiveauEtude = profiles.reduce(
    (acc, p) => {
      acc[p.niveauEtude] = (acc[p.niveauEtude] || 0) + 1
      return acc
    },
    {} as Record<string, number>
  )

  const inscriptionsParMois = [
    { mois: "Jan", count: profiles.filter((p) => p.dateInscription.startsWith("2025-01")).length },
    { mois: "Fev", count: profiles.filter((p) => p.dateInscription.startsWith("2025-02")).length },
    { mois: "Mar", count: profiles.filter((p) => p.dateInscription.startsWith("2025-03")).length },
    { mois: "Avr", count: profiles.filter((p) => p.dateInscription.startsWith("2025-04")).length },
    { mois: "Mai", count: profiles.filter((p) => p.dateInscription.startsWith("2025-05")).length },
  ]

  return {
    total,
    valides,
    enAttente,
    rejetes,
    parSecteur,
    parCategorie,
    parNiveauEtude,
    inscriptionsParMois,
  }
}
